const userActionTypes = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  EMAIL_SIGNIN_PENDING: "EMAIL_SIGNIN_PENDING",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNOUT_PENDING: "SIGNOUT_PENDING",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILED: "SIGNOUT_FAILED",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  ADD_PRODUCT_PENDING: "ADD_PRODUCT_PENDING",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ONFETCH: "ONFETCH",
  DATA_SERVER: "DATA_SERVER",
  FILE_SERVER: "FILE_SERVER",
  ADD_TABLE: "ADD_TABLE",
  ADD_CURRENT_TABLE: "ADD_CURRENT_TABLE"
};

export default userActionTypes;
